### ISSUE TITLE
crashes when closing app while using force-fullscreen on it

### ISSUE THREAD

**Issue by MrSwedish** [WayfireWM/wayfire-plugins-extra#88] opened 2021-06-12 15:54 UTC
does it on every app i tried

**Comment by soreau** [comment] 2021-06-12 15:59
How are you closing the application? Here when I use Alt+F4 or the menu on xfce4-terminal, it doesn't crash wayfire.

**Comment by MrSwedish** [comment] 2021-06-12 16:01
yeah, i'm alt+f4'ing or clsing via the apps way

**Comment by MrSwedish** [comment] 2021-06-12 16:01
wait, let me try sometihginh

**Comment by MrSwedish** [comment] 2021-06-12 16:08
nothing worked

**Comment by soreau** [comment] 2021-06-12 16:10
What version of wayfire are you using?

**Comment by MrSwedish** [comment] 2021-06-12 16:14
aur/wayfire 0.7.1-3 (+16 1.02) (Installed)
    3D wayland compositor

**Comment by soreau** [comment] 2021-06-12 16:16
I'm using latest git but I can't think of anything that has changed that would fix this.. I have tried with native wayland surfaces as well as with xwayland. Does it happen if you force-fullscreen a terminal and type `exit`?

**Comment by soreau** [comment] 2021-06-12 16:18
It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.

**Comment by MrSwedish** [comment] 2021-06-12 16:20
> I'm using latest git but I can't think of anything that has changed that would fix this.. I have tried with native wayland surfaces as well as with xwayland. Does it happen if you force-fullscreen a terminal and type `exit`?

yes

**Comment by MrSwedish** [comment] 2021-06-12 16:24
> It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.

[output](https://gist.github.com/MrSwedish/7b1c751949d876b0407e22f3bd75d3bc)
it dies while trying to save itslef

**Comment by soreau** [comment] 2021-06-12 16:33
> > It also could be your configuration but the log would be most useful as it should contain a backtrace. Just start wayfire with `wayfire &> /tmp/wayfire.log` then cause the crash and post the log file.
> 
> [output](https://gist.github.com/MrSwedish/7b1c751949d876b0407e22f3bd75d3bc)

This does not contain the backtrace at the end. It does not appear that wayfire crashed in this log. Are you causing wayfire to crash before posting the log?

**Comment by MrSwedish** [comment] 2021-06-12 16:37
oh, so after the crash?

**Comment by soreau** [comment] 2021-06-12 16:38
yes and if you have to restart wayfire again to post the log, don't use &> /tmp/wayfire.log because that will overwrite the log file

**Comment by MrSwedish** [comment] 2021-06-12 16:50
[wafires.log](https://github.com/WayfireWM/wayfire-plugins-extra/files/6642566/wafires.log)
this time I started wayfire from the tty
not from the terminal inside wayfire (lol)

**Comment by soreau** [comment] 2021-06-12 16:55
Hm, I can't really tell what's going wrong there, but maybe @ammen99 has some idea. Since I can't reproduce here with wayfire git, I'd say try upgrading to latest -git packages and see if the problem persists.

**Comment by MrSwedish** [comment] 2021-06-12 16:57
alright

**Comment by MrSwedish** [comment] 2021-06-12 17:13
works on git!

**Comment by MrSwedish** [comment] 2021-06-12 17:30
but now i don't get audio

**Comment by MrSwedish** [comment] 2021-06-12 18:01
sorry, the audio thing was just me

**Comment by soreau** [comment] 2021-06-12 19:56
👍

**Closed by soreau** 2021-06-12 19:56 UTC
